server:
  port: 7002
spring:
  application:
    name: eureka-server # eureka服务集群的name要相同
eureka:
  client:
    register-with-eureka: true # 将eureka服务器注册为服务
    fetch-registry: true # 获取注册信息
    service-url:
      defaultZone: 'http://eureka7001.com:7001/eureka,http://eureka7003.com:7003/eureka' # 将注册服务器地址写成另外两个集群的地址，此处用peer2和peer3代理localhost或127.0.0.1
  instance:
    hostname: eureka7002.com # 注意hostname不能为空
